"""
code_generator.py — Generates a C header (config.h) from a RobotConfig.
The firmware reads this header via #include and uses #ifdef guards.
No Qt imports — pure Python.
"""
from __future__ import annotations
import os
import hashlib
import datetime
from .config_model import RobotConfig


def generate_config_h(cfg: RobotConfig, output_path: str) -> str:
    """Write config.h to output_path. Returns the file content string."""
    lines: list[str] = []

    def w(s: str = "") -> None:
        lines.append(s)

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    w("// ============================================================")
    w("// AUTO-GENERATED by PAROL6 Firmware Configurator")
    w(f"// Profile : {cfg.name}")
    w(f"// Generated: {now}")
    w(f"// Phase    : {cfg.phase}")
    w("// DO NOT EDIT THIS FILE MANUALLY — edit via the GUI.")
    w("// ============================================================")
    w()
    w("#pragma once")
    w()

    # ------------------------------------------------------------------
    # Feature Flags
    # ------------------------------------------------------------------
    w("// ── Feature Flags ─────────────────────────────────────────────")
    f = cfg.features

    w(f"#define FEATURE_INTERPOLATOR_LOCK {int(f.lock_interpolator)}")
    w(f"#define FEATURE_ALPHABETA_FILTER  {int(f.alphabeta_filter)}")
    w(f"#define FEATURE_VEL_FEEDFORWARD   {int(f.velocity_feedforward)}")
    w(f"#define FEATURE_WATCHDOG          {int(f.watchdog)}")
    w(f"#define FEATURE_SAFETY_SUPERVISOR {int(f.safety_supervisor)}")
    w(f"#define FEATURE_ANTI_GLITCH       {int(f.anti_glitch_filter)}")
    w(f"#define FEATURE_VEL_DEADBAND      {int(f.velocity_deadband)}")
    w(f"#define FEATURE_ENCODER_TEST_MODE {int(f.encoder_test_mode)}")
    w(f"#define FEATURE_SINE_TEST_MODE    {int(f.sine_test_mode)}")
    w(f"#define FEATURE_HARDWARE_PWM      {int(f.hardware_pwm_step_dir)}")
    w(f"#define FEATURE_HARDWARE_ENCODER  {int(f.hardware_encoder_qtimer)}")
    w(f"#define FIXED_STEP_FREQ_HZ        {f.fixed_step_freq_hz}  // 0=off")
    w(f"#define VELOCITY_DEADBAND_RAD_S   {f.velocity_deadband_rad_s}f")
    w()

    # ------------------------------------------------------------------
    # Communications & Timing
    # ------------------------------------------------------------------
    w("// ── Communications & Timing ───────────────────────────────────")
    c = cfg.comms
    transport_map = {"UART_115200": 0, "USB_CDC_HS": 1, "ETHERNET": 2}
    w(f"#define TRANSPORT_MODE            {transport_map.get(c.transport, 1)}  // 0=UART 1=USB_HS 2=ETH")
    w(f"#define ROS_COMMAND_RATE_HZ       {c.ros_command_rate_hz}")
    w(f"#define FEEDBACK_RATE_HZ          {c.feedback_rate_hz}")
    w(f"#define CONTROL_LOOP_RATE_HZ      {c.control_loop_rate_hz}")
    w(f"#define CONTROL_LOOP_PERIOD_US    {1_000_000 // c.control_loop_rate_hz}")
    w(f"#define COMMAND_TIMEOUT_MS        {c.command_timeout_ms}")
    if c.transport == "ETHERNET":
        w(f'#define ETH_IP                    "{c.ethernet_ip}"')
        w(f'#define ETH_GATEWAY               "{c.ethernet_gateway}"')
        w(f'#define ETH_SUBNET                "{c.ethernet_subnet}"')
        w(f"#define ETH_PORT                  {c.ethernet_port}")
    w()

    # ------------------------------------------------------------------
    # Number of joints
    # ------------------------------------------------------------------
    enabled_joints = [j for j in cfg.joints if j.enabled]
    w("// ── Joint Count ───────────────────────────────────────────────")
    w(f"#define NUM_AXES                  {len(cfg.joints)}")
    w()

    # ------------------------------------------------------------------
    # Per-Joint Pin Arrays
    # ------------------------------------------------------------------
    def arr(name: str, values: list, fmt: str = "{}") -> None:
        vals_str = ", ".join(fmt.format(v) for v in values)
        w(f"static const int {name}[{len(values)}] = {{{vals_str}}};")

    def farr(name: str, values: list, suffix: str = "f") -> None:
        vals_str = ", ".join(f"{v}{suffix}" for v in values)
        w(f"static const float {name}[{len(values)}] = {{{vals_str}}};")

    def barr(name: str, values: list) -> None:
        vals_str = ", ".join("1" if v else "0" for v in values)
        w(f"static const bool {name}[{len(values)}] = {{{vals_str}}};")

    w("// ── Pin Assignments ───────────────────────────────────────────")
    arr("STEP_PINS",    [j.step_pin    for j in cfg.joints])
    arr("DIR_PINS",     [j.dir_pin     for j in cfg.joints])
    arr("ENCODER_PINS", [j.encoder_pin for j in cfg.joints])
    w()

    w("// ── Motor Configuration ───────────────────────────────────────")
    farr("GEAR_RATIOS",  [j.gear_ratio    for j in cfg.joints])
    arr( "MICROSTEPS",   [j.microsteps    for j in cfg.joints])
    barr("DIR_INVERT",   [j.dir_invert    for j in cfg.joints])
    barr("ROS_DIR_INVERT", [j.ros_dir_invert for j in cfg.joints])  # Read by parol6_system.cpp via xacro
    barr("JOINT_ENABLED",[j.enabled       for j in cfg.joints])
    farr("MAX_VEL_RAD_S",[j.max_vel_rad_s for j in cfg.joints])

    # Precomputed steps per radian
    import math
    steps_per_rad = [
        (j.steps_per_rev * j.microsteps * j.gear_ratio) / (2.0 * math.pi)
        for j in cfg.joints
    ]
    farr("STEPS_PER_RAD", [round(v, 4) for v in steps_per_rad])
    w()

    w("// ── Control Gains ─────────────────────────────────────────────")
    farr("KP_GAINS",    [j.kp    for j in cfg.joints])
    farr("KI_GAINS",    [j.ki    for j in cfg.joints])
    farr("MAX_INTEGRAL",[j.max_integral for j in cfg.joints])
    farr("AB_ALPHA",    [j.alpha for j in cfg.joints])
    farr("AB_BETA",     [j.beta  for j in cfg.joints])
    w()

    w("// ── Limit Switches ────────────────────────────────────────────")
    barr("LIMIT_ENABLED",  [j.limit.enabled     for j in cfg.joints])
    arr( "LIMIT_PINS",     [j.limit.pin          for j in cfg.joints])
    # LIMIT_ACTIVE_HIGH and LIMIT_PULL are consumed by LimitSwitch.configure() in main.cpp setup().
    # LIMIT_POLARITY and LIMIT_TYPE are generated for future firmware use — not yet consumed at runtime.
    arr( "LIMIT_POLARITY", [0 if j.limit.polarity == "FALLING" else 1 for j in cfg.joints])  # [reserved]
    # Type: 0=NONE, 1=MECHANICAL, 2=NPN, 3=PNP
    type_map = {"NONE": 0, "MECHANICAL": 1, "INDUCTIVE_NPN": 2, "INDUCTIVE_PNP": 3}
    arr( "LIMIT_TYPE",     [type_map.get(j.limit.switch_type, 0) for j in cfg.joints])  # [reserved]
    # Pull resistor: 0=INPUT, 1=INPUT_PULLUP, 2=INPUT_PULLDOWN (matches Arduino constants in firmware)
    # For NPN/Mechanical → INPUT_PULLUP; For PNP → INPUT_PULLDOWN; NONE → INPUT_PULLUP (safe default)
    pull_map = {"INPUT": 0, "INPUT_PULLUP": 1, "INPUT_PULLDOWN": 2}
    arr( "LIMIT_PULL",     [pull_map.get(j.limit.pull, 1) for j in cfg.joints])
    # Active-high flag: true when triggered == HIGH (PNP), false when triggered == LOW (NPN/Mechanical)
    barr("LIMIT_ACTIVE_HIGH", [j.limit.polarity == "RISING" for j in cfg.joints])
    w()

    w("// ── Homing Configuration ──────────────────────────────────────")
    arr( "HOMING_ORDER",   cfg.homing.order)
    farr("HOME_OFFSETS_RAD", [j.home_offset_rad for j in cfg.joints])
    arr( "HOMING_SPEED",   [j.homing_speed_steps_s  for j in cfg.joints])
    arr( "HOMED_OFFSET",   [j.homed_position_steps  for j in cfg.joints])
    # STANDBY_POS: target position after homing — generated for future use, not yet consumed in firmware.
    arr( "STANDBY_POS",    [j.standby_position_steps for j in cfg.joints])  # [reserved]
    w()

    # Config fingerprint (hash of content so exports can be reproducible)
    content = "\n".join(lines)
    fingerprint = hashlib.sha256(content.encode()).hexdigest()[:12]
    lines.insert(7, f"// Fingerprint: {fingerprint}")

    result = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as fh:
        fh.write(result)

    return result

def generate_joint_limits(cfg: RobotConfig, output_path: str) -> None:
    """Write joint_limits.yaml for MoveIt based on the configurator's MAX_VEL_RAD_S."""
    lines = ["# AUTO-GENERATED by PAROL6 Firmware Configurator", "joint_limits:"]
    
    for i, j in enumerate(cfg.joints):
        name = f"joint_L{i+1}"
        lines.append(f"  {name}:")
        lines.append(f"    has_velocity_limits: true")
        lines.append(f"    max_velocity: {j.max_vel_rad_s}  # Synced from config.h MAX_VEL_RAD_S")
        lines.append(f"    has_acceleration_limits: true")
        lines.append(f"    max_acceleration: {j.max_accel_rad_s2}  # Synced from config.h MAX_ACCEL_RAD_S2")
        
    result = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as fh:
        fh.write(result)

